In [1]:
from pathlib import Path

import pandas as pd
import numpy as np

In [2]:
ROOT = Path.cwd()

if ROOT.name == "notebooks":
    ROOT = ROOT.parent

RAW = ROOT / "data" / "raw"

print("Project folder:", ROOT)
print("Raw data folder:", RAW)

Project folder: c:\Users\isc\Desktop\portfolio\olist-ecommerce-analysis
Raw data folder: c:\Users\isc\Desktop\portfolio\olist-ecommerce-analysis\data\raw

In [3]:
expected_files = [
    "olist_customers_dataset.csv",
    "olist_geolocation_dataset.csv",
    "olist_order_items_dataset.csv",
    "olist_order_payments_dataset.csv",
    "olist_order_reviews_dataset.csv",
    "olist_orders_dataset.csv",
    "olist_products_dataset.csv",
    "olist_sellers_dataset.csv",
    "product_category_name_translation.csv",
]

for filename in expected_files:
    path = RAW / filename

    if path.exists():
        print(f"FOUND   : {filename}")
    else:
        print(f"MISSING : {filename}")

FOUND   : olist_customers_dataset.csv
FOUND   : olist_geolocation_dataset.csv
FOUND   : olist_order_items_dataset.csv
FOUND   : olist_order_payments_dataset.csv
FOUND   : olist_order_reviews_dataset.csv
FOUND   : olist_orders_dataset.csv
FOUND   : olist_products_dataset.csv
FOUND   : olist_sellers_dataset.csv
FOUND   : product_category_name_translation.csv

In [4]:
customers = pd.read_csv(RAW / "olist_customers_dataset.csv")
geolocation = pd.read_csv(RAW / "olist_geolocation_dataset.csv")
order_items = pd.read_csv(RAW / "olist_order_items_dataset.csv")
payments = pd.read_csv(RAW / "olist_order_payments_dataset.csv")
reviews = pd.read_csv(RAW / "olist_order_reviews_dataset.csv")
orders = pd.read_csv(RAW / "olist_orders_dataset.csv")
products = pd.read_csv(RAW / "olist_products_dataset.csv")
sellers = pd.read_csv(RAW / "olist_sellers_dataset.csv")
categories = pd.read_csv(RAW / "product_category_name_translation.csv")

In [5]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,10/2/2017 10:56,10/2/2017 11:07,10/4/2017 19:55,10/10/2017 21:25,10/18/2017 0:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,7/24/2018 20:41,7/26/2018 3:24,7/26/2018 14:31,8/7/2018 15:27,8/13/2018 0:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,8/8/2018 8:38,8/8/2018 8:55,8/8/2018 13:50,8/17/2018 18:06,9/4/2018 0:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,11/18/2017 19:28,11/18/2017 19:45,11/22/2017 13:39,12/2/2017 0:28,12/15/2017 0:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2/13/2018 21:18,2/13/2018 22:20,2/14/2018 19:46,2/16/2018 18:17,2/26/2018 0:00

In [6]:
orders.shape

(99441, 8)

In [7]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [8]:
orders["order_id"].is_unique

True

In [9]:
order_items["order_id"].is_unique

False

In [10]:
order_items["order_id"].value_counts().head(10)

order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
428a2f660dc84138d969ccd69a0ab6d5    15
9ef13efd6949e4573a18964dd1bbe7f5    15
73c8ab38f07dc94389065f7eba4f297a    14
9bdc4d4c71aa1de4606060929dee888c    14
37ee401157a3a0b28c9c6d0ed8c3b24b    13
2c2a19b5703863c908512d135aa6accc    12
3a213fcdfe7d98be74ea0dc05a8b31ae    12
Name: count, dtype: int64

In [11]:
payments["order_id"].is_unique

False

In [12]:
payments["order_id"].value_counts().head(10)

order_id
fa65dad1b0e818e3ccc5cb0e39231352    29
ccf804e764ed5650cd8759557269dc13    26
285c2e15bebd4ac83635ccc563dc71f4    22
895ab968e7bb0d5659d16cd74cd1650c    21
ee9ca989fc93ba09a6eddc250ce01742    19
fedcd9f7ccdc8cba3a18defedd1a5547    19
21577126c19bf11a0b91592e5844ba78    15
4bfcba9e084f46c8e3cb49b0fa6e6159    15
3c58bffb70dcf45f12bdf66a3c215905    14
4689b1816de42507a7d63a4617383c59    14
Name: count, dtype: int64

In [13]:
tables = {
    "customers": customers,
    "geolocation": geolocation,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "orders": orders,
    "products": products,
    "sellers": sellers,
    "categories": categories,
}

In [14]:
for name, df in tables.items():
    print(f"{name:15} rows={df.shape[0]:,}   columns={df.shape[1]}")

customers       rows=99,441   columns=5
geolocation     rows=1,000,163   columns=5
order_items     rows=112,650   columns=7
payments        rows=103,886   columns=5
reviews         rows=99,224   columns=7
orders          rows=99,441   columns=8
products        rows=32,951   columns=9
sellers         rows=3,095   columns=4
categories      rows=71   columns=2

In [15]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,10/2/2017 10:56,10/2/2017 11:07,10/4/2017 19:55,10/10/2017 21:25,10/18/2017 0:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,7/24/2018 20:41,7/26/2018 3:24,7/26/2018 14:31,8/7/2018 15:27,8/13/2018 0:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,8/8/2018 8:38,8/8/2018 8:55,8/8/2018 13:50,8/17/2018 18:06,9/4/2018 0:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,11/18/2017 19:28,11/18/2017 19:45,11/22/2017 13:39,12/2/2017 0:28,12/15/2017 0:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2/13/2018 21:18,2/13/2018 22:20,2/14/2018 19:46,2/16/2018 18:17,2/26/2018 0:00

In [16]:
orders.sample(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
40429,cccd803c5e04b33ad226cf7beae0f127,940d5acb47467a9a136576b8ec497c29,delivered,6/2/2017 15:35,6/3/2017 2:15,6/5/2017 13:00,6/6/2017 13:50,6/19/2017 0:00
30229,dcb97cff5ad47d9a584ac61d5b857f41,fe84bd242903da1b257065a81f330118,delivered,8/8/2018 17:06,8/8/2018 17:15,8/14/2018 10:11,8/20/2018 21:32,8/20/2018 0:00
69711,4a42846a6eed9d15714fe30181399f2a,85a7452fba73610a36dfad568e8ee016,unavailable,2/17/2017 13:57,2/17/2017 14:05,NaN,NaN,3/20/2017 0:00
9570,e866dc21d680405383a1dcad4821f2df,8eba5d36d26af896fb5a068bdb7980ad,delivered,10/9/2017 19:57,10/10/2017 20:06,10/11/2017 15:47,10/19/2017 23:17,10/31/2017 0:00
97671,0aeb20ab92028bf31d5d8b2314b03092,5faa65fc45f1cf27ea90df480d25129d,delivered,2/7/2018 16:35,2/7/2018 16:49,2/9/2018 1:43,2/14/2018 23:43,2/23/2018 0:00

In [17]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 19.9 MB

In [18]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [19]:
orders.isna().mean() * 100

order_id                         0.000000
customer_id                      0.000000
order_status                     0.000000
order_purchase_timestamp         0.000000
order_approved_at                0.160899
order_delivered_carrier_date     1.793023
order_delivered_customer_date    2.981668
order_estimated_delivery_date    0.000000
dtype: float64

In [20]:
missing_orders = pd.DataFrame({
    "missing_count": orders.isna().sum(),
    "missing_percent": orders.isna().mean() * 100
})

missing_orders

                               missing_count  missing_percent
order_id                                   0         0.000000
customer_id                                0         0.000000
order_status                               0         0.000000
order_purchase_timestamp                   0         0.000000
order_approved_at                        160         0.160899
order_delivered_carrier_date            1783         1.793023
order_delivered_customer_date           2965         2.981668
order_estimated_delivery_date              0         0.000000

In [21]:
orders.duplicated().sum()

np.int64(0)

In [22]:
orders["order_id"].nunique()

99441

In [23]:
len(orders)

99441

In [24]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [25]:
orders["order_status"].value_counts(normalize=True) * 100

order_status
delivered      97.020344
shipped         1.113223
canceled        0.628513
unavailable     0.612423
invoiced        0.315765
processing      0.302692
created         0.005028
approved        0.002011
Name: proportion, dtype: float64

In [26]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 17.9 MB

In [27]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,9/19/2017 9:45,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,5/3/2017 11:05,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,1/18/2018 14:48,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,8/15/2018 10:10,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2/13/2017 13:57,199.90,18.14

In [28]:
order_items.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [29]:
order_items.duplicated().sum()

np.int64(0)

In [30]:
order_items["order_id"].is_unique

False

In [31]:
order_items[["order_id", "order_item_id"]].duplicated().sum()

np.int64(0)

In [32]:
order_items.describe()

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [33]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [34]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 8.1 MB

In [35]:
payments.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [36]:
payments.duplicated().sum()

np.int64(0)

In [37]:
payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [38]:
payments["payment_installments"].describe()

count    103886.000000
mean          2.853349
std           2.687051
min           0.000000
25%           1.000000
50%           1.000000
75%           4.000000
max          24.000000
Name: payment_installments, dtype: float64

In [39]:
payments["payment_value"].describe()

count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

In [40]:
customers.shape

(99441, 5)

In [41]:
customers["customer_id"].nunique()

99441

In [42]:
customers["customer_unique_id"].nunique()

96096

In [43]:
customers["customer_unique_id"].value_counts().head(10)

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
1b6c7548a2a1f9037c1fd3ddfed95f33     7
6469f99c1f9dfae7733b25662e7f1782     7
ca77025e7201e3b30c44b472ff346268     7
47c1a3033b8b77b3ab6e109eb4d5fdf3     6
dc813062e0fc23409cd255f7f53c7074     6
63cfc61cee11cbe306bff5857d00bfe4     6
f0e310a6839dce9de1638e0fe5ab282a     6
de34b16117594161a6a89c50b289d35a     6
Name: count, dtype: int64

In [44]:
profile_summary = []

for name, df in tables.items():
    profile_summary.append({
        "table": name,
        "rows": len(df),
        "columns": len(df.columns),
        "duplicate_rows": df.duplicated().sum(),
        "missing_cells": df.isna().sum().sum(),
        "missing_percent": df.isna().sum().sum() / df.size * 100
    })

profile_summary = pd.DataFrame(profile_summary)

profile_summary

,table,rows,columns,duplicate_rows,missing_cells,missing_percent
0,customers,99441,5,0,0,0.000000
1,geolocation,1000163,5,261831,0,0.000000
2,order_items,112650,7,0,0,0.000000
3,payments,103886,5,0,0,0.000000
4,reviews,99224,7,0,145903,21.006295
5,orders,99441,8,0,4908,0.616949
6,products,32951,9,0,2448,0.825468
7,sellers,3095,4,0,0,0.000000
8,categories,71,2,0,0,0.000000

In [45]:
print("=== TABLE PROFILE SUMMARY ===")
display(profile_summary)

print("\n=== ORDER STATUS COUNTS ===")
display(orders["order_status"].value_counts())

print("\n=== CUSTOMER IDENTIFIERS ===")
print("Rows in customers table:", len(customers))
print("Unique customer_id:", customers["customer_id"].nunique())
print("Unique customer_unique_id:", customers["customer_unique_id"].nunique())

print("\n=== ORDER ITEM COMPOSITE KEY DUPLICATES ===")
print(
    order_items[["order_id", "order_item_id"]]
    .duplicated()
    .sum()
)

print("\n=== PAYMENT TYPES ===")
display(payments["payment_type"].value_counts())

=== TABLE PROFILE SUMMARY ===

,table,rows,columns,duplicate_rows,missing_cells,missing_percent
0,customers,99441,5,0,0,0.000000
1,geolocation,1000163,5,261831,0,0.000000
2,order_items,112650,7,0,0,0.000000
3,payments,103886,5,0,0,0.000000
4,reviews,99224,7,0,145903,21.006295
5,orders,99441,8,0,4908,0.616949
6,products,32951,9,0,2448,0.825468
7,sellers,3095,4,0,0,0.000000
8,categories,71,2,0,0,0.000000

=== ORDER STATUS COUNTS ===

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

=== CUSTOMER IDENTIFIERS ===
Rows in customers table: 99441
Unique customer_id: 99441
Unique customer_unique_id: 96096

=== ORDER ITEM COMPOSITE KEY DUPLICATES ===
0

=== PAYMENT TYPES ===

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [46]:
missing_orders = pd.DataFrame({
    "missing_count": orders.isna().sum(),
    "missing_percent": orders.isna().mean() * 100
})

display(missing_orders)

                               missing_count  missing_percent
order_id                                   0         0.000000
customer_id                                0         0.000000
order_status                               0         0.000000
order_purchase_timestamp                   0         0.000000
order_approved_at                        160         0.160899
order_delivered_carrier_date            1783         1.793023
order_delivered_customer_date           2965         2.981668
order_estimated_delivery_date              0         0.000000

In [47]:
orders.loc[
    orders["order_delivered_customer_date"].isna(),
    "order_status"
].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [48]:
orders.loc[
    (orders["order_status"] == "delivered") &
    (orders["order_delivered_customer_date"].isna())
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,11/28/2017 17:44,11/28/2017 17:56,11/30/2017 18:12,NaN,12/18/2017 0:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,6/20/2018 6:58,6/20/2018 7:19,6/25/2018 8:05,NaN,7/16/2018 0:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,7/1/2018 17:05,7/1/2018 17:15,7/3/2018 13:57,NaN,7/30/2018 0:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,7/1/2018 22:05,7/1/2018 22:15,7/3/2018 13:57,NaN,7/30/2018 0:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,7/1/2018 21:14,7/1/2018 21:29,7/3/2018 9:28,NaN,7/24/2018 0:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,5/25/2017 23:22,5/25/2017 23:30,NaN,NaN,6/23/2017 0:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,6/8/2018 12:09,6/8/2018 12:36,6/12/2018 14:10,NaN,6/26/2018 0:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,6/27/2018 16:09,6/27/2018 16:29,7/3/2018 19:26,NaN,7/19/2018 0:00

In [49]:
orders.loc[
    (orders["order_status"] == "delivered") &
    (orders["order_delivered_customer_date"].isna())
].shape

(8, 8)

In [50]:
date_columns = [
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date"
]

for col in date_columns:
    print(f"\n=== Missing {col} by order status ===")
    display(
        orders.loc[
            orders[col].isna(),
            "order_status"
        ].value_counts()
    )

=== Missing order_approved_at by order status ===

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

=== Missing order_delivered_carrier_date by order status ===

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

=== Missing order_delivered_customer_date by order status ===

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [51]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [52]:
geolocation.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='str')

In [53]:
geolocation["geolocation_zip_code_prefix"].nunique()

19015

In [54]:
len(geolocation)

1000163

In [55]:
geolocation["geolocation_zip_code_prefix"].value_counts().head(10)

geolocation_zip_code_prefix
24220    1146
24230    1102
38400     965
35500     907
11680     879
22631     832
30140     810
11740     788
38408     773
28970     743
Name: count, dtype: int64

In [56]:
geolocation[
    geolocation["geolocation_zip_code_prefix"] == 24220
].head(20)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
470805,24220,-22.905817,-43.106989,niteroi,RJ
470811,24220,-22.902306,-43.112545,niteroi,RJ
470812,24220,-22.904567,-43.110491,niteroi,RJ
470820,24220,-22.902575,-43.109192,niteroi,RJ
470821,24220,-22.907500,-43.106170,niteroi,RJ
470823,24220,-22.904319,-43.113001,niteroi,RJ
470824,24220,-22.899014,-43.106746,niteroi,RJ
470826,24220,-22.907401,-43.098585,niteroi,RJ
470828,24220,-22.903061,-43.109014,niteroi,RJ
470829,24220,-22.901422,-43.110802,niteroi,RJ
470839,24220,-22.899325,-43.108217,niteroi,RJ
470840,24220,-22.902553,-43.105805,niteroi,RJ
470844,24220,-22.899014,-43.106746,niteroi,RJ
470846,24220,-22.908591,-43.107320,niteroi,RJ
470851,24220,-22.899746,-43.112179,niterói,RJ
470853,24220,-22.906557,-43.111618,niteroi,RJ
470855,24220,-22.902175,-43.109950,niteroi,RJ
470856,24220,-22.901401,-43.102772,niteroi,RJ
470859,24220,-22.901616,-43.113823,niteroi,RJ
470870,24220,-22.904009,-43.112701,niteroi,RJ

In [57]:
review_missing = pd.DataFrame({
    "missing_count": reviews.isna().sum(),
    "missing_percent": reviews.isna().mean() * 100
})

display(review_missing)

                         missing_count  missing_percent
review_id                            0         0.000000
order_id                             0         0.000000
review_score                         0         0.000000
review_comment_title             87656        88.341530
review_comment_message           58247        58.702532
review_creation_date                 0         0.000000
review_answer_timestamp              0         0.000000

In [58]:
reviews["review_score"].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [59]:
reviews["review_score"].describe()

count    99224.000000
mean         4.086421
std          1.347579
min          1.000000
25%          4.000000
50%          5.000000
75%          5.000000
max          5.000000
Name: review_score, dtype: float64

In [60]:
reviews["review_score"].isna().sum()

np.int64(0)

In [61]:
product_missing = pd.DataFrame({
    "missing_count": products.isna().sum(),
    "missing_percent": products.isna().mean() * 100
})

display(product_missing)

                            missing_count  missing_percent
product_id                              0         0.000000
product_category_name                 610         1.851234
product_name_lenght                   610         1.851234
product_description_lenght            610         1.851234
product_photos_qty                    610         1.851234
product_weight_g                        2         0.006070
product_length_cm                       2         0.006070
product_height_cm                       2         0.006070
product_width_cm                        2         0.006070

In [62]:
product_categories = set(
    products["product_category_name"].dropna().unique()
)

translated_categories = set(
    categories["product_category_name"].dropna().unique()
)

untranslated_categories = product_categories - translated_categories

untranslated_categories

{'pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos'}

In [63]:
invalid_order_customers = orders.loc[
    ~orders["customer_id"].isin(customers["customer_id"])
]

len(invalid_order_customers)

0

In [64]:
invalid_item_orders = order_items.loc[
    ~order_items["order_id"].isin(orders["order_id"])
]

len(invalid_item_orders)

0

In [65]:
invalid_payment_orders = payments.loc[
    ~payments["order_id"].isin(orders["order_id"])
]

len(invalid_payment_orders)

0

In [66]:
invalid_item_products = order_items.loc[
    ~order_items["product_id"].isin(products["product_id"])
]

len(invalid_item_products)

0

In [67]:
invalid_item_sellers = order_items.loc[
    ~order_items["seller_id"].isin(sellers["seller_id"])
]

len(invalid_item_sellers)

0

In [68]:
display(
    order_items[
        [
            "price",
            "freight_value"
        ]
    ].describe()
)

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

In [69]:
print("Negative prices:",
      (order_items["price"] < 0).sum())

print("Zero prices:",
      (order_items["price"] == 0).sum())

print("Negative freight:",
      (order_items["freight_value"] < 0).sum())

print("Zero freight:",
      (order_items["freight_value"] == 0).sum())

Negative prices: 0
Zero prices: 0
Negative freight: 0
Zero freight: 383

In [70]:
display(
    payments[
        [
            "payment_installments",
            "payment_value"
        ]
    ].describe()
)

       payment_installments  payment_value
count         103886.000000  103886.000000
mean               2.853349     154.100380
std                2.687051     217.494064
min                0.000000       0.000000
25%                1.000000      56.790000
50%                1.000000     100.000000
75%                4.000000     171.837500
max               24.000000   13664.080000

In [71]:
print("Negative payment values:",
      (payments["payment_value"] < 0).sum())

print("Zero payment values:",
      (payments["payment_value"] == 0).sum())

print("Zero installments:",
      (payments["payment_installments"] == 0).sum())

print("Negative installments:",
      (payments["payment_installments"] < 0).sum())

Negative payment values: 0
Zero payment values: 9
Zero installments: 2
Negative installments: 0

In [72]:
payments[
    payments["payment_type"] == "not_defined"
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0

In [73]:
reviews["order_id"].is_unique

False

In [74]:
reviews["order_id"].value_counts().head(10)

order_id
c88b1d1b157a9999ce368f218a407141    3
df56136b8031ecd28e200bb18e6ddb2e    3
03c939fd7fd3b38f8485a0f95798f1f6    3
8e17072ec97ce29f0e1f111e598b0c85    3
cf73e2cb1f4a9480ed70c154da3d954a    2
169d7e0fd71d624d306f132acd791cbe    2
1c308eca3f339414a92e518e2a2e5ee9    2
2002ea16e75277eaa0b5d78632048540    2
1d297b4800ed1a3c5b0944d84c01ee99    2
0176a6846bcb3b0d3aa3116a9a768597    2
Name: count, dtype: int64

In [75]:
orders_customers = orders.merge(
    customers[
        [
            "customer_id",
            "customer_unique_id"
        ]
    ],
    on="customer_id",
    how="left"
)

In [76]:
customer_order_counts = (
    orders_customers
    .groupby("customer_unique_id")["order_id"]
    .nunique()
    .sort_values(ascending=False)
)

customer_order_counts.head(20)

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
1b6c7548a2a1f9037c1fd3ddfed95f33     7
6469f99c1f9dfae7733b25662e7f1782     7
ca77025e7201e3b30c44b472ff346268     7
47c1a3033b8b77b3ab6e109eb4d5fdf3     6
12f5d6e1cbf93dafd9dcc19095df0b3d     6
63cfc61cee11cbe306bff5857d00bfe4     6
dc813062e0fc23409cd255f7f53c7074     6
de34b16117594161a6a89c50b289d35a     6
f0e310a6839dce9de1638e0fe5ab282a     6
35ecdf6858edc6427223b64804cf028e     5
394ac4de8f3acb14253c177f0e15bc58     5
56c8638e7c058b98aae6d74d2dd6ea23     5
74cb1ad7e6d5674325c1f99b5ea30d82     5
fe81bb32c243a86b2f86fbf053fe6140     5
5e8f38a9a1c023f3db718edcf926a2db     5
4e65032f1f574189fb793bac5a867bbc     5
b4e4f24de1e8725b74e4a1f4975116ed     5
083ca1aa470c280236380973a48f77c6     4
Name: order_id, dtype: int64

In [77]:
(customer_order_counts > 1).sum()

np.int64(2997)

In [78]:
(customer_order_counts > 1).mean() * 100

np.float64(3.1187562437562435)

In [79]:
date_columns = [
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date"
]

for col in date_columns:
    print(f"\n=== Missing {col} by order status ===")

    display(
        orders.loc[
            orders[col].isna(),
            "order_status"
        ].value_counts()
    )

=== Missing order_approved_at by order status ===

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

=== Missing order_delivered_carrier_date by order status ===

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

=== Missing order_delivered_customer_date by order status ===

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [80]:
delivered_missing_date = orders.loc[
    (orders["order_status"] == "delivered")
    & (orders["order_delivered_customer_date"].isna())
]

print("Delivered orders with no customer delivery date:",
      len(delivered_missing_date))

display(delivered_missing_date.head(8))

Delivered orders with no customer delivery date: 8

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,11/28/2017 17:44,11/28/2017 17:56,11/30/2017 18:12,NaN,12/18/2017 0:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,6/20/2018 6:58,6/20/2018 7:19,6/25/2018 8:05,NaN,7/16/2018 0:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,7/1/2018 17:05,7/1/2018 17:15,7/3/2018 13:57,NaN,7/30/2018 0:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,7/1/2018 22:05,7/1/2018 22:15,7/3/2018 13:57,NaN,7/30/2018 0:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,7/1/2018 21:14,7/1/2018 21:29,7/3/2018 9:28,NaN,7/24/2018 0:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,5/25/2017 23:22,5/25/2017 23:30,NaN,NaN,6/23/2017 0:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,6/8/2018 12:09,6/8/2018 12:36,6/12/2018 14:10,NaN,6/26/2018 0:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,6/27/2018 16:09,6/27/2018 16:29,7/3/2018 19:26,NaN,7/19/2018 0:00

In [81]:
zero_payments = payments.loc[
    payments["payment_value"] == 0
]

display(zero_payments)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0

In [82]:
zero_payments["payment_type"].value_counts()

payment_type
voucher        6
not_defined    3
Name: count, dtype: int64

In [83]:
display(
    zero_payments.merge(
        orders[
            [
                "order_id",
                "order_status",
                "order_purchase_timestamp"
            ]
        ],
        on="order_id",
        how="left"
    )
)

,order_id,payment_sequential,payment_type,payment_installments,payment_value,order_status,order_purchase_timestamp
0,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0,delivered,1/24/2018 23:24
1,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0,shipped,4/20/2017 12:45
2,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0,delivered,10/26/2017 23:51
3,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0,canceled,9/3/2018 14:14
4,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0,canceled,8/28/2018 15:26
5,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0,delivered,6/8/2017 21:18
6,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0,shipped,4/20/2017 12:45
7,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0,canceled,8/28/2018 20:05
8,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0,delivered,5/27/2017 19:20

In [84]:
zero_installments = payments.loc[
    payments["payment_installments"] == 0
]

display(zero_installments)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [85]:
undefined_payments = payments.loc[
    payments["payment_type"] == "not_defined"
]

display(undefined_payments)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0

In [86]:
review_counts = reviews["order_id"].value_counts()

print(
    "Orders with more than one review:",
    (review_counts > 1).sum()
)

print(
    "Maximum reviews for a single order:",
    review_counts.max()
)

Orders with more than one review: 547
Maximum reviews for a single order: 3

In [87]:
display(review_counts.head(10))

order_id
c88b1d1b157a9999ce368f218a407141    3
df56136b8031ecd28e200bb18e6ddb2e    3
03c939fd7fd3b38f8485a0f95798f1f6    3
8e17072ec97ce29f0e1f111e598b0c85    3
cf73e2cb1f4a9480ed70c154da3d954a    2
169d7e0fd71d624d306f132acd791cbe    2
1c308eca3f339414a92e518e2a2e5ee9    2
2002ea16e75277eaa0b5d78632048540    2
1d297b4800ed1a3c5b0944d84c01ee99    2
0176a6846bcb3b0d3aa3116a9a768597    2
Name: count, dtype: int64

In [88]:
example_multi_review_order = review_counts.index[0]

display(
    reviews.loc[
        reviews["order_id"] == example_multi_review_order
    ]
)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
1985,ffb8cff872a625632ac983eb1f88843c,c88b1d1b157a9999ce368f218a407141,3,NaN,NaN,7/22/2017 0:00,7/26/2017 13:41
82525,202b5f44d09cd3cfc0d6bd12f01b044c,c88b1d1b157a9999ce368f218a407141,5,NaN,NaN,7/22/2017 0:00,7/26/2017 13:40
89360,fb96ea2ef8cce1c888f4d45c8e22b793,c88b1d1b157a9999ce368f218a407141,5,NaN,NaN,7/21/2017 0:00,7/26/2017 13:45

In [89]:
metadata_columns = [
    "product_category_name",
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty"
]

products[metadata_columns].isna().sum()

product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
dtype: int64

In [90]:
missing_category_products = products.loc[
    products["product_category_name"].isna()
]

display(
    missing_category_products[
        metadata_columns
    ].isna().sum()
)

product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
dtype: int64

In [91]:
missing_product_ids = set(
    missing_category_products["product_id"]
)

affected_items = order_items.loc[
    order_items["product_id"].isin(missing_product_ids)
]

print(
    "Order-item rows involving products with missing metadata:",
    len(affected_items)
)

print(
    "Unique affected products actually sold:",
    affected_items["product_id"].nunique()
)

print(
    "Unique affected orders:",
    affected_items["order_id"].nunique()
)

Order-item rows involving products with missing metadata: 1603
Unique affected products actually sold: 610
Unique affected orders: 1451

In [92]:
dimension_columns = [
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

missing_dimensions = products.loc[
    products[dimension_columns].isna().any(axis=1)
]

display(missing_dimensions)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [93]:
invalid_review_orders = reviews.loc[
    ~reviews["order_id"].isin(orders["order_id"])
]

len(invalid_review_orders)

0

In [94]:
print(
    "Geolocation rows:",
    len(geolocation)
)

print(
    "Exact duplicate rows:",
    geolocation.duplicated().sum()
)

print(
    "Unique ZIP prefixes:",
    geolocation["geolocation_zip_code_prefix"].nunique()
)

Geolocation rows: 1000163
Exact duplicate rows: 261831
Unique ZIP prefixes: 19015

In [95]:
zip_counts = (
    geolocation["geolocation_zip_code_prefix"]
    .value_counts()
)

display(zip_counts.head(10))

geolocation_zip_code_prefix
24220    1146
24230    1102
38400     965
35500     907
11680     879
22631     832
30140     810
11740     788
38408     773
28970     743
Name: count, dtype: int64

In [96]:
example_zip = zip_counts.index[0]

display(
    geolocation.loc[
        geolocation["geolocation_zip_code_prefix"] == example_zip
    ].head(20)
)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
470805,24220,-22.905817,-43.106989,niteroi,RJ
470811,24220,-22.902306,-43.112545,niteroi,RJ
470812,24220,-22.904567,-43.110491,niteroi,RJ
470820,24220,-22.902575,-43.109192,niteroi,RJ
470821,24220,-22.907500,-43.106170,niteroi,RJ
470823,24220,-22.904319,-43.113001,niteroi,RJ
470824,24220,-22.899014,-43.106746,niteroi,RJ
470826,24220,-22.907401,-43.098585,niteroi,RJ
470828,24220,-22.903061,-43.109014,niteroi,RJ
470829,24220,-22.901422,-43.110802,niteroi,RJ
470839,24220,-22.899325,-43.108217,niteroi,RJ
470840,24220,-22.902553,-43.105805,niteroi,RJ
470844,24220,-22.899014,-43.106746,niteroi,RJ
470846,24220,-22.908591,-43.107320,niteroi,RJ
470851,24220,-22.899746,-43.112179,niterói,RJ
470853,24220,-22.906557,-43.111618,niteroi,RJ
470855,24220,-22.902175,-43.109950,niteroi,RJ
470856,24220,-22.901401,-43.102772,niteroi,RJ
470859,24220,-22.901616,-43.113823,niteroi,RJ
470870,24220,-22.904009,-43.112701,niteroi,RJ